package View;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import perbankan.Bank;
import perbankan.Nasabah;

public class NasabahViews extends javax.swing.JPanel {
    private MainFrame mainFrame;
    private Nasabah nasabah;

    /**
     * Creates new form NasabahViews
     */
    public NasabahViews(MainFrame mainFrame, Nasabah nasabah) {
        initComponents();
        this.nasabah = nasabah;
        this.mainFrame = mainFrame;
        valuePemilikRekening.setText(": " + nasabah.getNamaAwal() 
                + " " + nasabah.getNamaAkhir());
        updateSaldo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTarikSaldo = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        formTitle = new javax.swing.JLabel();
        labelPemilikRekening = new javax.swing.JLabel();
        valuePemilikRekening = new javax.swing.JLabel();
        labelSaldo = new javax.swing.JLabel();
        valueSaldo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnTambahSaldo = new javax.swing.JButton();
        btnTransferSaldo = new javax.swing.JButton();

        btnTarikSaldo.setText("Tarik Saldo");
        btnTarikSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTarikSaldoActionPerformed(evt);
            }
        });

        btnCancel.setText("Logout");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        formTitle.setFont(new java.awt.Font("Inter ExtraBold", 1, 20)); // NOI18N
        formTitle.setText("Informasi Rekening");

        labelPemilikRekening.setFont(new java.awt.Font("Inter Medium", 0, 12)); // NOI18N
        labelPemilikRekening.setText("Pemilik Rekening");

        valuePemilikRekening.setFont(new java.awt.Font("Inter Medium", 0, 12)); // NOI18N
        valuePemilikRekening.setText(": jLabel3");

        labelSaldo.setFont(new java.awt.Font("Inter Medium", 0, 12)); // NOI18N
        labelSaldo.setText("Saldo");

        valueSaldo.setFont(new java.awt.Font("Inter Medium", 0, 12)); // NOI18N
        valueSaldo.setText(": jLabel3");

        jLabel1.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jLabel1.setText("Silakan pilih menu berikut");

        btnTambahSaldo.setText("Tambah Saldo");
        btnTambahSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahSaldoActionPerformed(evt);
            }
        });

        btnTransferSaldo.setText("Transfer Saldo");
        btnTransferSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransferSaldoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(formTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelPemilikRekening)
                            .addComponent(labelSaldo))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(valuePemilikRekening)
                            .addComponent(valueSaldo)))
                    .addComponent(jLabel1)
                    .addComponent(btnTambahSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                    .addComponent(btnTarikSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTransferSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(formTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPemilikRekening)
                    .addComponent(valuePemilikRekening))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSaldo)
                    .addComponent(valueSaldo))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTambahSaldo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTarikSaldo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTransferSaldo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancel)
                .addContainerGap(18, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTarikSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTarikSaldoActionPerformed
        String input = JOptionPane.showInputDialog(this,
            "Masukkan jumlah saldo yang ingin ditarik:", "0");

        if (input != null) {
            try {
                int jumlahUang = Integer.parseInt(input);

                if (!nasabah.getTabungan().ambilUang(jumlahUang)) {
                    JOptionPane.showMessageDialog(this, "Saldo tidak cukup!");
                    return;
                }
                JOptionPane.showMessageDialog(this, "Tarik saldo berhasil!");
                updateSaldo();
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this,
                    "Masukkan jumlah yang valid!\nInput harus berupa angka");
            }
        }
    }//GEN-LAST:event_btnTarikSaldoActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        mainFrame.showView(new HomeView(mainFrame));
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnTambahSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahSaldoActionPerformed
        String input = JOptionPane.showInputDialog(this,
            "Masukkan jumlah saldo yang ingin ditambahkan:", "0");

        if(input != null) {
            try {
                int jumlahUang = Integer.parseInt(input);
                nasabah.getTabungan().simpanUang(jumlahUang);
                JOptionPane.showMessageDialog(this,
                    "Tambah saldo berhasil!");
                updateSaldo();                
            } catch(NumberFormatException e) {
                JOptionPane.showMessageDialog(this,
                    "Masukkan jumlah yang valid!\nInput harus berupa angka");
            }
        }
    }//GEN-LAST:event_btnTambahSaldoActionPerformed

    private void btnTransferSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferSaldoActionPerformed
        mainFrame.showView(new TransferView(mainFrame, nasabah));
    }//GEN-LAST:event_btnTransferSaldoActionPerformed

    private void updateSaldo() {
        int saldo = nasabah.getTabungan().getSaldo();
        DecimalFormat formatter = new DecimalFormat("###,###");
        String saldoFormatted = formatter.format(saldo);
        valueSaldo.setText(": Rp " + saldoFormatted);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnTambahSaldo;
    private javax.swing.JButton btnTarikSaldo;
    private javax.swing.JButton btnTransferSaldo;
    private javax.swing.JLabel formTitle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelPemilikRekening;
    private javax.swing.JLabel labelSaldo;
    private javax.swing.JLabel valuePemilikRekening;
    private javax.swing.JLabel valueSaldo;
    // End of variables declaration//GEN-END:variables
}
