/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import perbankan.Nasabah;

/**
 *
 * @author Asus
 */
public class NasabahView extends javax.swing.JFrame {
    private Nasabah nasabah;
    private PerbankanView perbankanView;
    /**
     * Creates new form NasabahView
     */
    public NasabahView(Nasabah nasabah, PerbankanView perbankanView) {
        initComponents();
        this.nasabah = nasabah;
        this.perbankanView = perbankanView;
        valuePemilikRekening.setText(": " + nasabah.getNamaAwal() 
                + " " + nasabah.getNamaAkhir());
        updateSaldo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        formTitle = new javax.swing.JLabel();
        labelPemilikRekening = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        valuePemilikRekening = new javax.swing.JLabel();
        labelSaldo = new javax.swing.JLabel();
        valueSaldo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnTambahSaldo = new javax.swing.JButton();
        btnTarikSaldo = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        formTitle.setFont(new java.awt.Font("Inter ExtraBold", 1, 20)); // NOI18N
        formTitle.setText("Informasi Rekening");

        labelPemilikRekening.setFont(new java.awt.Font("Inter Medium", 0, 12)); // NOI18N
        labelPemilikRekening.setText("Pemilik Rekening");

        valuePemilikRekening.setFont(new java.awt.Font("Inter Medium", 0, 12)); // NOI18N
        valuePemilikRekening.setText(": jLabel3");

        labelSaldo.setFont(new java.awt.Font("Inter Medium", 0, 12)); // NOI18N
        labelSaldo.setText("Saldo");

        valueSaldo.setFont(new java.awt.Font("Inter Medium", 0, 12)); // NOI18N
        valueSaldo.setText(": jLabel3");

        jLabel1.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jLabel1.setText("Silakan pilih menu berikut");

        btnTambahSaldo.setText("Tambah Saldo");
        btnTambahSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahSaldoActionPerformed(evt);
            }
        });

        btnTarikSaldo.setText("Tarik Saldo");
        btnTarikSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTarikSaldoActionPerformed(evt);
            }
        });

        btnCancel.setText("Batal");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(formTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelPemilikRekening)
                                    .addComponent(labelSaldo))
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(valuePemilikRekening)
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel2))
                                    .addComponent(valueSaldo)))
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnTambahSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnTarikSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(formTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPemilikRekening)
                    .addComponent(jLabel2)
                    .addComponent(valuePemilikRekening))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSaldo)
                    .addComponent(valueSaldo))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambahSaldo)
                    .addComponent(btnTarikSaldo)
                    .addComponent(btnCancel))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahSaldoActionPerformed
        String input = JOptionPane.showInputDialog(this, 
                "Masukkan jumlah saldo yang ingin ditambahkan:", "0");
        
        if(input != null) {
            try {
                int jumlahUang = Integer.parseInt(input);
                nasabah.getTabungan().simpanUang(jumlahUang);
                updateSaldo();

                if (perbankanView != null) {
                    perbankanView.updateTable();
                }
            } catch(NumberFormatException e) {
                JOptionPane.showMessageDialog(this, 
                        "Masukkan jumlah yang valid!\nInput harus berupa angka");
            }
        }
    }//GEN-LAST:event_btnTambahSaldoActionPerformed

    private void btnTarikSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTarikSaldoActionPerformed
        String input = JOptionPane.showInputDialog(this, 
                "Masukkan jumlah saldo yang ingin ditarik:", "0");
        
        if (input != null) {
            try {
                int jumlahUang = Integer.parseInt(input);

                if (!nasabah.getTabungan().ambilUang(jumlahUang))
                    JOptionPane.showMessageDialog(this, "Saldo tidak cukup!");
                updateSaldo();

                if (perbankanView != null)
                    perbankanView.updateTable();
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, 
                        "Masukkan jumlah yang valid!\nInput harus berupa angka");
            }
        }
    }//GEN-LAST:event_btnTarikSaldoActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed
    
    private void updateSaldo() {
        int saldo = nasabah.getTabungan().getSaldo();
        DecimalFormat formatter = new DecimalFormat("###,###");
        String saldoFormatted = formatter.format(saldo);
        valueSaldo.setText(": Rp " + saldoFormatted);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NasabahView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NasabahView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NasabahView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NasabahView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnTambahSaldo;
    private javax.swing.JButton btnTarikSaldo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel formTitle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelPemilikRekening;
    private javax.swing.JLabel labelSaldo;
    private javax.swing.JLabel valuePemilikRekening;
    private javax.swing.JLabel valueSaldo;
    // End of variables declaration//GEN-END:variables
}
