/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import perbankan.Bank;
import perbankan.Nasabah;

/**
 *
 * @author Asus
 */
public class PerbankanView extends javax.swing.JFrame {

    /**
     * Creates new form PerbankanView
     */
    private Bank bank;
    private DefaultTableModel tableModel;
    private boolean isRowSelected = false;
    private int pointedIndex;
    
    public PerbankanView() {
        initComponents();
        this.bank = new Bank();
        this.tableModel = (DefaultTableModel)tableNasabah.getModel();
        this.tableModel.setRowCount(0);
        
        tableNasabah.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    isRowSelected = tableNasabah.getSelectedRow() != -1;
                    updateButtonVisibility();
                }
            }
        });
        updateButtonVisibility();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        labelNamaAwal = new javax.swing.JLabel();
        formTitle = new javax.swing.JLabel();
        inputNamaAwal = new javax.swing.JTextField();
        labelNamaAkhir = new javax.swing.JLabel();
        inputNamaAkhir = new javax.swing.JTextField();
        btnNasabahAction = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableNasabah = new javax.swing.JTable();
        btnHapusNasabah = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnTransaksi = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelNamaAwal.setFont(new java.awt.Font("Inter Medium", 0, 12)); // NOI18N
        labelNamaAwal.setText("Nama Awal");

        formTitle.setFont(new java.awt.Font("Inter ExtraBold", 1, 20)); // NOI18N
        formTitle.setText("Bank");

        labelNamaAkhir.setFont(new java.awt.Font("Inter Medium", 0, 12)); // NOI18N
        labelNamaAkhir.setText("Nama Akhir");

        btnNasabahAction.setText("Tambah");
        btnNasabahAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNasabahActionActionPerformed(evt);
            }
        });

        tableNasabah.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Nama Awal", "Nama Akhir", "Saldo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableNasabah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableNasabahMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableNasabah);
        if (tableNasabah.getColumnModel().getColumnCount() > 0) {
            tableNasabah.getColumnModel().getColumn(0).setMaxWidth(50);
            tableNasabah.getColumnModel().getColumn(1).setResizable(false);
        }

        btnHapusNasabah.setText("Hapus");
        btnHapusNasabah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusNasabahActionPerformed(evt);
            }
        });

        btnCancel.setText("Batal");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnTransaksi.setText("Transaksi");
        btnTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransaksiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNamaAwal)
                            .addComponent(labelNamaAkhir))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputNamaAkhir)
                            .addComponent(inputNamaAwal)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNasabahAction)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHapusNasabah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTransaksi)))
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(formTitle)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(formTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNamaAwal)
                    .addComponent(inputNamaAwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputNamaAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNamaAkhir))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNasabahAction)
                    .addComponent(btnHapusNasabah)
                    .addComponent(btnCancel)
                    .addComponent(btnTransaksi))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNasabahActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNasabahActionActionPerformed
        String namaAwal = inputNamaAwal.getText();
        String namaAkhir = inputNamaAkhir.getText();
        
        if(!namaAwal.equals("") && !namaAkhir.equals("")) {
            if(isRowSelected) {
                bank.updateNasabah(tableNasabah.getSelectedRow(), namaAwal, namaAkhir);
                JOptionPane.showMessageDialog(this, "Data berhasil diubah!");
            } else {
                bank.tambahNasabah(namaAwal, namaAkhir);
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan!");
            }
            updateTable();
            clearTextField();
        } else {
            JOptionPane.showMessageDialog(this, "Mohon lengkapi data!");
        }
    }//GEN-LAST:event_btnNasabahActionActionPerformed

    private void btnHapusNasabahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusNasabahActionPerformed
        if(isRowSelected) {
            int selectedRow = tableNasabah.getSelectedRow();
            bank.deleteNasabah(selectedRow);
            updateTable();
            clearTextField();
        } else {
            if(tableNasabah.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this,
                        "Data masih kosong!");
            } else {
                JOptionPane.showMessageDialog(this, 
                        "Pilih data yang ingin dihapus terlebih dahulu!");
            }
        }
        updateButtonVisibility();
    }//GEN-LAST:event_btnHapusNasabahActionPerformed

    private void tableNasabahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableNasabahMouseClicked
        int row = tableNasabah.rowAtPoint(evt.getPoint());
        this.pointedIndex = tableNasabah.getSelectedRow();
        
        if(row >= 0) {
            String namaAwal = bank.getNasabah(pointedIndex).getNamaAwal();
            String namaAkhir = bank.getNasabah(pointedIndex).getNamaAkhir();
            
            inputNamaAwal.setText(namaAwal);
            inputNamaAkhir.setText(namaAkhir);
        }
    }//GEN-LAST:event_tableNasabahMouseClicked

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        updateButtonVisibility();
        tableNasabah.getSelectionModel().clearSelection();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransaksiActionPerformed
        int selectedRow = tableNasabah.getSelectedRow();
        Nasabah nasabah = bank.getNasabah(selectedRow);
        new NasabahView(nasabah, this).setVisible(true);
    }//GEN-LAST:event_btnTransaksiActionPerformed
    
    public void updateTable() {
        int jumlahNasabah = bank.getJumlahNasabah();
        tableModel.setRowCount(0);

        for (int i = 0; i < jumlahNasabah; i++) {
            String namaAwal = bank.getNasabah(i).getNamaAwal();
            String namaAkhir = bank.getNasabah(i).getNamaAkhir();
            int saldo = bank.getNasabah(i).getTabungan().getSaldo();
            DecimalFormat formatter = new DecimalFormat("###,###");
            String saldoFormatted = formatter.format(saldo);
            
            tableModel.addRow(new Object[]{i + 1, bank.getNasabah(i).getNamaAwal(), 
                bank.getNasabah(i).getNamaAkhir(), "Rp " + saldoFormatted});
        }
    }
    
    private void updateButtonVisibility() {
        isRowSelected = tableNasabah.getSelectedRow() != -1;

        if (isRowSelected) {
            int selectedRow = tableNasabah.getSelectedRow();
            int nasabahIndex = selectedRow;
            inputNamaAwal.setText(bank.getNasabah(nasabahIndex).getNamaAwal());
            inputNamaAkhir.setText(bank.getNasabah(nasabahIndex).getNamaAkhir());
            btnNasabahAction.setText("Ubah");
            btnHapusNasabah.setVisible(true);
            btnCancel.setVisible(true);
            btnTransaksi.setVisible(true);
        } else {
            clearTextField();
            btnNasabahAction.setText("Tambah");
            btnHapusNasabah.setVisible(false);
            btnCancel.setVisible(false);
            btnTransaksi.setVisible(false);
        }
    }
    
    private void clearTextField() {
        inputNamaAwal.setText("");
        inputNamaAkhir.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PerbankanView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PerbankanView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PerbankanView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PerbankanView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PerbankanView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnHapusNasabah;
    private javax.swing.JButton btnNasabahAction;
    private javax.swing.JButton btnTransaksi;
    private javax.swing.JLabel formTitle;
    private javax.swing.JTextField inputNamaAkhir;
    private javax.swing.JTextField inputNamaAwal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelNamaAkhir;
    private javax.swing.JLabel labelNamaAwal;
    private javax.swing.JTable tableNasabah;
    // End of variables declaration//GEN-END:variables
}
