package View;

import javax.swing.JOptionPane;
import perbankan.Bank;
import perbankan.Nasabah;
import services.DatabaseService;

public class TransferView extends javax.swing.JPanel {
    private MainFrame mainFrame;
    private Nasabah nasabah;
    private Bank bank;
    /**
     * Creates new form TransferView
     */
    public TransferView(MainFrame mainFrame, Nasabah nasabah) {
        initComponents();
        this.mainFrame = mainFrame;
        this.nasabah = nasabah;
        this.bank = DatabaseService.getBank();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jScrollBar1 = new javax.swing.JScrollBar();
        titleTransferSaldo = new javax.swing.JLabel();
        labelRekeningTujuan = new javax.swing.JLabel();
        inputRekeningTujuan = new javax.swing.JTextField();
        labelNominal = new javax.swing.JLabel();
        inputNominal = new javax.swing.JTextField();
        btnTransfer = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        jToggleButton1.setText("jToggleButton1");

        titleTransferSaldo.setFont(new java.awt.Font("Inter ExtraBold", 1, 20)); // NOI18N
        titleTransferSaldo.setText("Transfer Saldo");

        labelRekeningTujuan.setFont(new java.awt.Font("Inter Medium", 0, 12)); // NOI18N
        labelRekeningTujuan.setText("Rek. Tujuan");

        labelNominal.setFont(new java.awt.Font("Inter Medium", 0, 12)); // NOI18N
        labelNominal.setText("Nominal");

        btnTransfer.setText("Transfer");
        btnTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransferActionPerformed(evt);
            }
        });

        btnBack.setText("Kembali");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnTransfer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelRekeningTujuan)
                                .addComponent(labelNominal))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(inputRekeningTujuan, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                                .addComponent(inputNominal)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(9, 9, 9)
                                    .addComponent(titleTransferSaldo))))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(titleTransferSaldo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRekeningTujuan)
                    .addComponent(inputRekeningTujuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNominal)
                    .addComponent(inputNominal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnTransfer)
                .addGap(18, 18, 18)
                .addComponent(btnBack)
                .addContainerGap(18, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        mainFrame.showView(new NasabahViews(mainFrame, nasabah));
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferActionPerformed
        int jumlahTransfer = Integer.parseInt(inputNominal.getText());
        String penerima = inputRekeningTujuan.getText();
        String pengirim = nasabah.getUsername();
        boolean isTransferSuccess = bank.transferAntarNasabah(pengirim, 
                penerima, jumlahTransfer);
        
        if (pengirim.equals(penerima)) {
            JOptionPane.showMessageDialog(this, 
                    "Transfer gagal! Anda tidak dapat mentransfer ke diri sendiri.");
            return;
        }
        
        if (isTransferSuccess) {
            JOptionPane.showMessageDialog(this, 
                    "Transfer Berhasil!");
            inputRekeningTujuan.setText("");
            inputNominal.setText("");
        } else {
            JOptionPane.showMessageDialog(this, 
                    "Transfer gagal! Periksa saldo atau rekening tujuan.");
        }
    }//GEN-LAST:event_btnTransferActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnTransfer;
    private javax.swing.JTextField inputNominal;
    private javax.swing.JTextField inputRekeningTujuan;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel labelNominal;
    private javax.swing.JLabel labelRekeningTujuan;
    private javax.swing.JLabel titleTransferSaldo;
    // End of variables declaration//GEN-END:variables
}
